// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UUIDGenerator is an autogenerated mock type for the UUIDGenerator type
type UUIDGenerator struct {
	mock.Mock
}

type UUIDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *UUIDGenerator) EXPECT() *UUIDGenerator_Expecter {
	return &UUIDGenerator_Expecter{mock: &_m.Mock}
}

// GenerateAsString provides a mock function with given fields:
func (_m *UUIDGenerator) GenerateAsString() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// UUIDGenerator_GenerateAsString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAsString'
type UUIDGenerator_GenerateAsString_Call struct {
	*mock.Call
}

// GenerateAsString is a helper method to define mock.On call
func (_e *UUIDGenerator_Expecter) GenerateAsString() *UUIDGenerator_GenerateAsString_Call {
	return &UUIDGenerator_GenerateAsString_Call{Call: _e.mock.On("GenerateAsString")}
}

func (_c *UUIDGenerator_GenerateAsString_Call) Run(run func()) *UUIDGenerator_GenerateAsString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UUIDGenerator_GenerateAsString_Call) Return(_a0 string) *UUIDGenerator_GenerateAsString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UUIDGenerator_GenerateAsString_Call) RunAndReturn(run func() string) *UUIDGenerator_GenerateAsString_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewUUIDGenerator interface {
	mock.TestingT
	Cleanup(func())
}

// NewUUIDGenerator creates a new instance of UUIDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUUIDGenerator(t mockConstructorTestingTNewUUIDGenerator) *UUIDGenerator {
	mock := &UUIDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
